#!/usr/bin/env python3
"""
Publish scheduled articles from content/articles/queue/.

Queue files use the same KEY: Value header + markdown format as
content/articles/sources/ (see docs/PUBLISHING.md). The DATE: header is the
date the article goes live. On each run, every queue article whose DATE has
arrived (South African time, UTC+2) is:

  1. moved into content/articles/sources/
  2. built into articles/<slug>.html and registered in articles-data.json
     (by scripts/build-articles.py)
  3. added to the card grid in articles/index.html
     (the block between the AUTO-CARDS markers is regenerated)
  4. added to sitemap.xml

Runs daily from .github/workflows/publish-scheduled.yml. Queue files whose
names start with "_" are ignored.

Usage:
  python3 scripts/publish-scheduled.py                  # publish due articles
  python3 scripts/publish-scheduled.py --date 2026-08-07  # pretend today is this date
  python3 scripts/publish-scheduled.py --dry-run        # report only, change nothing
  python3 scripts/publish-scheduled.py --rebuild-index  # regenerate index cards only
"""

import argparse
import html
import importlib.util
import json
import re
import shutil
import sys
from datetime import date, datetime, timedelta, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
QUEUE_DIR = ROOT / 'content' / 'articles' / 'queue'
SOURCES_DIR = ROOT / 'content' / 'articles' / 'sources'
DATA_FILE = ROOT / 'content' / 'articles' / 'data' / 'articles-data.json'
INDEX_FILE = ROOT / 'articles' / 'index.html'
SITEMAP_FILE = ROOT / 'sitemap.xml'

CARDS_START = '<!-- AUTO-CARDS:START (generated by scripts/publish-scheduled.py — do not edit by hand) -->'
CARDS_END = '<!-- AUTO-CARDS:END -->'

# SVG paths from the site's existing card icons, keyed by category.
CATEGORY_ICONS = {
    'Compliance':   'M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z',
    'Deductions':   'M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6',
    'Tax Planning': 'M13 7h8m0 0v8m0-8l-8 8-4-4-6 6',
    'Technology':   'M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z',
    'Business':     'M21 13.255A23.931 23.931 0 0112 15c-3.183 0-6.22-.62-9-1.745M16 6V4a2 2 0 00-2-2h-4a2 2 0 00-2 2v2m4 6h.01M5 20h14a2 2 0 002-2V8a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z',
}
DEFAULT_ICON = 'M9 7h6m0 10v-3m-3 3h.01M9 17h.01M9 11h.01M12 11h.01M15 11h.01M4 19h16a2 2 0 002-2V7a2 2 0 00-2-2H4a2 2 0 00-2 2v10a2 2 0 002 2z'

SAST = timezone(timedelta(hours=2))


def load_build_module():
    spec = importlib.util.spec_from_file_location(
        'build_articles', ROOT / 'scripts' / 'build-articles.py')
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def queue_files():
    if not QUEUE_DIR.is_dir():
        return []
    files = sorted(list(QUEUE_DIR.glob('*.md')) + list(QUEUE_DIR.glob('*.txt')))
    return [f for f in files if not f.name.startswith('_')]


def article_date(filepath):
    match = re.search(r'^DATE\s*:\s*(\d{4}-\d{2}-\d{2})', filepath.read_text(encoding='utf-8'), re.M)
    if not match:
        return None
    return date.fromisoformat(match.group(1))


def build_card(article, position):
    cover = 'abcd'[position % 4]
    reveal = ' data-reveal' if position % 3 == 0 else f' data-reveal data-reveal-delay="{(position % 3) * 80}"'
    icon = CATEGORY_ICONS.get(article.get('category', ''), DEFAULT_ICON)
    title = html.escape(article['title'])
    desc = html.escape(article.get('description', ''))
    category = html.escape(article.get('category', 'Tax Insights'))
    read_time = html.escape(article.get('readTime', ''))
    return f'''        <a class="card" href="{article['slug']}.html"{reveal}>
          <div class="cover cover-{cover}">
            <svg fill="none" viewBox="0 0 24 24" stroke-width="1.4"><path stroke-linecap="round" stroke-linejoin="round" d="{icon}"/></svg>
            <span class="tag">{category}</span>
          </div>
          <div class="card-body">
            <h3>{title}</h3>
            <p class="desc">{desc}</p>
            <span class="meta">{read_time}</span>
          </div>
        </a>'''


def rebuild_index():
    """Regenerate the article card grid in articles/index.html from articles-data.json."""
    data = json.loads(DATA_FILE.read_text(encoding='utf-8'))
    articles = sorted(data['articles'], key=lambda a: a.get('date', ''), reverse=True)
    cards = '\n'.join(build_card(a, i) for i, a in enumerate(articles))
    block = f'{CARDS_START}\n{cards}\n        {CARDS_END}'

    index_html = INDEX_FILE.read_text(encoding='utf-8')
    pattern = re.compile(re.escape(CARDS_START) + '.*?' + re.escape(CARDS_END), re.S)
    if not pattern.search(index_html):
        raise SystemExit(f'ERROR: AUTO-CARDS markers not found in {INDEX_FILE}')
    INDEX_FILE.write_text(pattern.sub(lambda _: block, index_html), encoding='utf-8')
    print(f'✓ Rebuilt article index ({len(articles)} cards)')


def update_sitemap(slugs_with_dates, today):
    sitemap = SITEMAP_FILE.read_text(encoding='utf-8')
    added = 0
    for slug, date_iso in slugs_with_dates:
        loc = f'https://inspiredtax.co.za/articles/{slug}.html'
        if loc in sitemap:
            continue
        entry = (f'  <url>\n'
                 f'    <loc>{loc}</loc>\n'
                 f'    <lastmod>{date_iso}</lastmod>\n'
                 f'    <changefreq>yearly</changefreq>\n'
                 f'    <priority>0.8</priority>\n'
                 f'  </url>\n\n')
        sitemap = sitemap.replace('</urlset>', entry + '</urlset>')
        added += 1

    # Bump the article index lastmod to reflect the new listing
    sitemap = re.sub(
        r'(<loc>https://inspiredtax\.co\.za/articles/index\.html</loc>\s*<lastmod>)\d{4}-\d{2}-\d{2}(</lastmod>)',
        lambda m: m.group(1) + today.isoformat() + m.group(2),
        sitemap)

    SITEMAP_FILE.write_text(sitemap, encoding='utf-8')
    print(f'✓ Sitemap updated ({added} new URL(s))')


def main():
    parser = argparse.ArgumentParser(description='Publish scheduled articles whose DATE has arrived.')
    parser.add_argument('--date', help='Treat this date (YYYY-MM-DD) as today, for testing.')
    parser.add_argument('--dry-run', action='store_true', help='Report what would publish; change nothing.')
    parser.add_argument('--rebuild-index', action='store_true', help='Only regenerate the article index card grid.')
    args = parser.parse_args()

    if args.rebuild_index:
        rebuild_index()
        return

    today = date.fromisoformat(args.date) if args.date else datetime.now(SAST).date()

    due = []
    for filepath in queue_files():
        pub_date = article_date(filepath)
        if pub_date is None:
            print(f'! Skipping {filepath.name}: no DATE: header', file=sys.stderr)
            continue
        if pub_date <= today:
            due.append((pub_date, filepath))

    if not due:
        remaining = len(queue_files())
        print(f'Nothing due on {today}. {remaining} article(s) still queued.')
        return

    due.sort()
    if args.dry_run:
        for pub_date, filepath in due:
            print(f'Would publish: {filepath.name} (scheduled {pub_date})')
        return

    published = []
    for pub_date, filepath in due:
        dest = SOURCES_DIR / filepath.name
        shutil.move(str(filepath), str(dest))
        published.append((filepath.stem, pub_date.isoformat()))
        print(f'→ Publishing: {filepath.stem} (scheduled {pub_date})')

    # Generate article HTML + register the new articles in articles-data.json
    build = load_build_module()
    import os
    cwd = os.getcwd()
    os.chdir(ROOT)
    try:
        build.build_articles()
    finally:
        os.chdir(cwd)

    rebuild_index()
    update_sitemap(published, today)

    for slug, _ in published:
        print(f'PUBLISHED: {slug}')
    print(f'{len(queue_files())} article(s) remain in the queue.')


if __name__ == '__main__':
    main()
